import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "normalize.css";
import "./main.sass";
import { Topbar } from "./components/Topbar/Topbar";
import localFont from "next/font/local";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const myFont = localFont({
  src: [
    {
      path: "../fonts/RoseGard.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-myfont",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Topbar></Topbar>
        {children}
      </body>
    </html>
  );
}
